# Generated by Django 2.0.6 on 2018-06-30 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название категории', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('ts', models.CharField(max_length=200)),
                ('organization', models.TextField(max_length=200)),
                ('address', models.CharField(max_length=500)),
                ('cash_total_sum', models.IntegerField(help_text='Сумма по чеку в копеках')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('count', models.IntegerField()),
                ('price', models.IntegerField(help_text='Цена в копейках')),
                ('producer', models.CharField(max_length=500)),
                ('category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='check.Category')),
            ],
        ),
    ]
