# Generated by Django 2.0.6 on 2018-07-10 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название категории', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('fiscalDocumentNumber', models.IntegerField(default=0, help_text='ФПД', primary_key=True, serialize=False)),
                ('dateTime', models.CharField(default='', help_text='Время покупки', max_length=200)),
                ('user', models.TextField(default='', help_text='Организация', max_length=200)),
                ('retailPlaceAddress', models.CharField(default='', help_text='Адрес магазина', max_length=500)),
                ('totalSum', models.IntegerField(default=0, help_text='Сумма по чеку в копеках')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('count', models.IntegerField()),
                ('price', models.IntegerField(help_text='Цена в копейках')),
                ('producer', models.CharField(max_length=500)),
                ('category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='check.Category')),
            ],
        ),
    ]
