# Generated by Django 2.0.6 on 2018-07-11 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='price',
            new_name='sum',
        ),
        migrations.RemoveField(
            model_name='item',
            name='count',
        ),
        migrations.AddField(
            model_name='item',
            name='cash_check',
            field=models.ForeignKey(default=0, on_delete=None, to='check.Check'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='producer',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
